### ISSUE TITLE
Dropping a key value pair in the json when importing json data into Sqlite Db using Sqlite porter

### ISSUE THREAD

**Issue by Priya-Ahuja** [dpa99c/cordova-sqlite-porter#12]
Hi..I am using SQLite porter for pushing the data into SQLite DB programmatically using importJsontodb method.However, the JSON I receive has some attributes that I need to ignore while pushing the data.Is there any possibility  I can achieve it by modifying the plugin?

**Comment by dpa99c** [comment]
Why don't you just modify the JSON object in your app logic before importing it? Why does the plugin need to know about your specific JSON structure?

By all means fork and modify the plugin, but I will not accept the changes as a pull request because they will not be generic and therefore not useful to anyone else outside your specific needs.

**Comment by Priya-Ahuja** [comment]
Yes, I can try modifying the JSON object before importing..but the additional JSON info coming, differs for all the tables so how should I write a generic code that can remove any extra info apart from columns info?
