### ISSUE TITLE
Passing the json with columns without null values?

### ISSUE THREAD

**Issue by Priya-Ahuja** [dpa99c/cordova-sqlite-porter#13]
I am receiving a JSON which only has valid values (not null)  but I am getting an error saying 15 columns are there and only 12 values are applied.If I pass the null values for all the columns then the query executes successfully. Is there any chance the plugin can support the JSON which only has valid values?

**Comment by dpa99c** [comment]
If I understand correctly, you want the plugin to assume that a missing column value is intentional, so it should assume the value is null? 

For example, in the case below, "Genre" is missing in the inserts data, so the plugin should assume it is null:

    var json = {
        "structure":{
            "tables":{
                "Artist":"([Id] PRIMARY KEY, [Title], [Genre])"
            }
        },
        "data":{
            "inserts":{
                "Artist":[
                    {"Id":"1","Title":"Fred"},
                    {"Id":"2","Title":"Bob"},
                    {"Id":"3","Title":"Jack"},
                    {"Id":"4","Title":"John"}
                ]
            }
        }
    };

**Comment by Priya-Ahuja** [comment]
Yes same....but let me elaborate the situation , I am making a hybrid cordova app using 2 plugins sqlite dbcopy and sqlite storage..Initialy I copy the db with blank schema in my tablet using the mentioned plugins. After that i make REST service calls and receive JSON to make the Insert statements in the table using sqlite-porter plugin. following is the Json Structure i am receiving 

"tablename": [
      "{\"col1\":-1,\"col2\":\"Aug 8, 2016 5:38:00 PM\"}"]

If a column has a null value its not coming in json , so while inserting i get an error saying
Failed to import SQL; message=sqlite3_prepare_v2 failure: table DETAILS has 15 columns but 12 values were supplied.

I searched but couldn't find a proper fix.Please guide.

**Comment by dpa99c** [comment]
I am inclined not to make the plugin silently insert null values if a column value is missing from the JSON structure. This is because it would be too easy to erroneously insert null values if column values were unintentionally missing. 

Aside from this, the plugin does not "know" the structure of the table you are inserting data into when you call `importJsonToDb()`, so it doesn't "know" which column names are missing and should have null values substituted. Since the JSON is ultimately turned into SQL INSERT statements which will throw an error if a column value is missing in an INSERT statement, the plugin would have to discover the table structure of each table being inserted into to ensure there were no missing column values and I think this is not worth the effort for such an edge case as yours.

Therefore I think the current behaviour is correct: that you must explicitly specify null values for columns that you don't have explicit values for.

However, I've just published a new version of the plugin (v0.1.3) which allows only table structure to be exported in the JSON dump and this should help you to achieve your goal:

Using your example above, let us say you have an empty database table with 3 columns created with the following SQL statement:

    CREATE TABLE tablename ([col1], [col2], [col3]);

You can use the `exportJsonFromDb()` command to export the JSON structure for reference:

    var tableStructure;
    cordova.plugins.sqlitePorter.exportDbToJson(db, {
        successFn: function(json, count){
            var tableName, tableDef, columnNames, colCount;
            tableStructure = {};
            for(tableName in json.structure.tables){
                tableDef = json.structure.tables[tableName];
                columnNames = tableDef.match(/\[([^\]]+)\]/g);
                for (colCount=0; colCount < columnNames.length; colCount++){
                    columnNames[colCount] = columnNames[colCount].replace(/\[|\]/g, '');
                }
                tableStructure[tableName] = columnNames;
            }
        },
        structureOnly: true
    });
    
You then receive your JSON structure which is missing some column values:

    var receivedJson = {
        "tablename":[
            {
                "col1": -1,
                "col2": "Aug 8, 2016 5:38:00 PM"
            },
            {
                "col2": "Aug 8, 2016 5:38:00 PM"
                "col3": "blah"
            }
        ]
    }
    
You can then use the table structure to fill in null values for the missing columns:

    var tableName, rows, rowNum, row, colName;
    for (tableName in receivedJson){
        rows = receivedJson[tableName];
        for (rowNum=0; rowNum<rows.length; rowNum++){
            row = rows[rowNum];
            for (colName in tableStructure[tableName]){
                if(!row[colName]){
                    // Fill in missing value with null
                    row[colName] = "NULL";
                }
            }
        }
    }
