### ISSUE TITLE
define composite key

### ISSUE THREAD

**Issue by ntimesc** [dpa99c/cordova-sqlite-porter#14]
wanted to create composite key where i want to define 3 columns as a primary key , can anyone tell me how do i achieve using this plugin

**Comment by dpa99c** [comment]
Since `importSqlToDb()` executes given SQL commands you can specify a composite primary key directly in the table creation statement:

    var sql = "CREATE TABLE MyTable (ColA INTEGER NOT NULL, ColB INTEGER NOT NULL, ColC INTEGER NOT NULL, PRIMARY KEY (ColA, ColB, ColC));"
    cordova.plugins.sqlitePorter.importSqlToDb(db, sql, {
        successFn: successFn,
        errorFn: errorFn,
        progressFn: progressFn
    });


The JSON structure section for `importJsonToDb()` takes the table creation SQL as the value for the table name key, hence you can also specify a composite primary key when creating the table:

    var json = {
        "structure":{
            "tables":{
                "MyTable":"(ColA INTEGER NOT NULL, ColB INTEGER NOT NULL, ColC INTEGER NOT NULL, PRIMARY KEY (ColA, ColB, ColC))"
            }
        }
    };
    cordova.plugins.sqlitePorter.importJsonToDb(db, json, {
        successFn: successFn,
        errorFn: errorFn,
        progressFn: progressFn,
        batchInsertSize: 500
    });
