### ISSUE TITLE
Export Selected data to JSON

### ISSUE THREAD

**Issue by jonatasfreitasv** [dpa99c/cordova-sqlite-porter#2]
Hi,

how i import Selected data to JSON ?

**Comment by dpa99c** [comment]
I'm not quite sure what you mean by this. Do you mean how can you select specific tables to dump to JSON rather than the entire database? 

If this is your question, then answer is you can't (currrently) - the plugin allows you to dump or restore an entire database, not selected tables. But if this is something you'd find useful, let me know.

If this is not your question, then please clarify with an example.

**Comment by jonatasfreitasv** [comment]
Hummm ok,
i need to select data in table and convert this result in JSON string, you know how to make this ?

**Comment by jonatasfreitasv** [comment]
i need to post selected data in JSON format...

**Comment by dpa99c** [comment]
This plugin is the wrong tool for the job to do a select of specific data in a specific table. It is intended for the more generic scenario of dumping an entire database.

You can use the [WebSQL API](http://www.databasejournal.com/sqletc/article.php/3903201/Using-the-Web-SQL-Database-API-in-HTML-5.htm) to select and retrieve the data from the database and [JSON.stringify()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) to convert the results object into a JSON string which you can POST to wherever.

Since your need is specific (the plugin cannot know what data you need to select), I will close this issue.

**Comment by ogunm** [comment]
Check out this [Sqlite Porter](https://github.com/dpa99c/cordova-sqlite-porter)
