### ISSUE TITLE
Incorrect string escaping of character sequence ''&\"

### ISSUE THREAD

**Issue by laurent-bettin** [dpa99c/cordova-sqlite-porter#24]
Hi it looks like the character sequence ''&\" is not escaped properly (test code below).
I'm not a sqlite specialist neither a regex one so i'm unable to suggest a solution.

Thanks.

```javascript
var json = {
   "structure":{
      "tables":{
         "test":"([Id] PRIMARY KEY, [Title])"
      },
      "otherSQL":[]
   },
   "data":{
      "inserts":{
         "test":[{
           "Id":"1",
           "Title":"''&\""
          }]
      }
   }
};

cordova.plugins.sqlitePorter.importJsonToDb(db, json);
```

```javascript
{
  "message":"Failed to import SQL; message=sqlite3_prepare_v2 failure: near \"&\": syntax error",
  "code":5,
  "statement":"INSERT OR REPLACE INTO test SELECT '1' AS 'Id', ''''&"
}
```

**Comment by dpa99c** [comment]
I've tested this scenario and can reproduce it - seems the issue is with multiple single quotes in the value.
Whilst it's definitely a bug, I haven't encountered it before as it's pretty uncommon is real database values - I haven't come across it in any real data in the apps in which I have used this plugin or in the [Chinook database](https://chinookdatabase.codeplex.com/) which is a test database used by the example project for this plugin to validate its functionality.
