### ISSUE TITLE
Expected 2 arguments but got 3

### ISSUE THREAD

**Issue by Raja77777** [dpa99c/cordova-sqlite-porter#35]
this.sqlitePorter.importJsonToDb(this.database, json,successfn)

Hi i am stucked in this and i want to know how to pass the 3rd parameter to importjsonTodb function.
Whenever i include the 3rd opts param it says expected 2 but u given 3 in cordova ionic.
Anyone can help please ??

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-sqlite-porter#importjsontodb), the syntax is:

    cordova.plugins.sqlitePorter.importJsonToDb(db, json, opts);

therefore your use of the API is wrong, it should be:

    this.sqlitePorter.importJsonToDb(this.database, json,{successFn : successfn});

However, if the Ionic Native wrapper is not accepting this 3rd argument, you should [raise the issue against Ionic Native](https://github.com/ionic-team/ionic-native/issues) because that's not part of this plugin.

In future please don't use the issues section for asking support questions: use StackOverflow or the Ionic forums.

**Comment by Raja77777** [comment]
Ok i will raise and also i want to know that this is the correct format to use
 'this.sqlitePorter.importJsonToDb(this.database, json,{successFn : successfn});'?
