### ISSUE TITLE
statement count missing 1 quantity

### ISSUE THREAD

**Issue by azn1viet** [dpa99c/cordova-sqlite-porter#5]
```
[{"catalog":"6191-1-001","lotcode":"RJM326","expiration":"06/01/200707/31/2008"},
{"catalog":"5532-G-616","lotcode":"MRPMJD","expiration":"06/01/200705/29/2012"},
{"catalog":"5532-G-409","lotcode":"M0VMJD","expiration":"06/01/200705/29/2012"},
{"catalog":"5530-G-416","lotcode":"MR8MJD","expiration":"06/01/200705/29/2012"},
{"catalog":"5551-G-320","lotcode":"Z541","expiration":"06/01/200705/29/2012"}]

console-via-logger.js:174 Imported 1/4 statements
console-via-logger.js:174 Imported 2/4 statements
console-via-logger.js:174 Imported 3/4 statements
console-via-logger.js:174 Imported 4/4 statements
```

I got it counted 4 but the  output should be 5.

**Comment by dpa99c** [comment]
When you pass a JSON structure to [`importJsonToDb()`](https://github.com/dpa99c/cordova-sqlite-porter#importjsontodb), the count is not the number of entries in the `data.inserts` key (which I assume is what the fragment of JSON you've posted relates to). This is because the structure may also contain updates and deletes also, which are not necessarily logical records. Instead, as the [documentation says](https://github.com/dpa99c/cordova-sqlite-porter#importjsontodb), successFn is passed the "total number of statements executed in the given SQL string". 

i.e. the count is the number of resulting SQL statements generated from the JSON structure. This count is what's useful (you should already know how many inserts you are passing in), because each SQL statement is executed sequentially, allowing you to track the progress of the sequential statement execution via progressFn and get the total in successFn.

For example, in the [example project](https://github.com/dpa99c/cordova-sqlite-porter-example), loading and importing [simple_dump.json](https://github.com/dpa99c/cordova-sqlite-porter-example/blob/master/www/json/simple_dump.json) (in the example app, select Database=Simple; Data format=JSON; Data type=Dump), the following JSON is imported:

```
{
  "structure":{
    "tables":{
      "Album":"([AlbumId] PRIMARY KEY, [Title])"
    },
    "otherSQL": [
      "CREATE UNIQUE INDEX Album_ID ON Album(AlbumId)"
    ]
  },
  "data":{
    "inserts":{
      "Album":[
        {
          "AlbumId":"1",
          "Title":"Fred"
        },
        {
          "AlbumId":"2",
          "Title":"Bob"
        },
        {
          "AlbumId":"3",
          "Title":"Tom"
        },
        {
          "AlbumId":"4",
          "Title":"Dick"
        },
        {
          "AlbumId":"5",
          "Title":"Harry"
        }
      ]
    }
  }
}
```

So the count passed to successFn should be 5 right? No. Because the resulting SQL generated from the JSON is:

```
DROP TABLE IF EXISTS Album;
CREATE TABLE Album([AlbumId] PRIMARY KEY, [Title]);
CREATE UNIQUE INDEX Album_ID ON Album(AlbumId);
INSERT OR REPLACE INTO Album SELECT '1' AS 'AlbumId', 'Fred' AS 'Title' UNION SELECT  '2', 'Bob' UNION SELECT  '3', 'Tom' UNION SELECT  '4', 'Dick' UNION SELECT  '5', 'Harry';
```

So the resulting count passed to succesFn is 4. 

The plugin using UNION SELECT to combine inserts, minimizing the number of INSERT statements and maximising speed.

Without seeing what other parameters you are passing in, I can't know the exact SQL being generated for your example above, but this is the reason the count is not as you expect it to be.

**Comment by azn1viet** [comment]
I got the db 5 records inserted is what exactly what I expected. I'm not sure about your answer why it says "Imported 4/4 statements" rather than "Imported 5/5 statements"

**Comment by dpa99c** [comment]
It's counting SQL statements, not records. If you don't understand, look at the source code.
